### ISSUE TITLE
Segmented Chinese characters should be regarded as a word

### ISSUE THREAD

**Issue by ip1200** [sgsinclair/Voyant#224]
Beta version cannot recognize segmented Chinese characters, while version 1.0 can do it well . Chinese segment using space to divide characters into meaning words, just like English. However, Beta considers the characters as singles ones, ignoring the existing space which combines characters as a meaningful word.
Except for this, some functions of the early version cannot handle segmented Chinese characters partly or completely. Such as Cirrus, Knots, Lava, Mandala and Word Count Fountain. Hope final 2.0 version can better handle Chinese.

PIC1 1.0 can recognize segemented  Chinese characters:
![ashampoo_snap_2015 11 25_22h19m29s_002_voyant tools- reveal your texts - google chrome](https://cloud.githubusercontent.com/assets/16018638/11400349/cd90d872-93c7-11e5-8e97-17fc9d9c83db.png)

PIC2 The beta cannot recognize segmented characters, but treat them as single characters.
![ashampoo_snap_2015 11 25_22h20m47s_003_voyant tools - google chrome](https://cloud.githubusercontent.com/assets/16018638/11400354/dc2c4ac4-93c7-11e5-8b6f-c5fb33fe1760.png)

PIC3 1.0 version of Timeradio cannot work properly (the trend line disappears)
![termradio](https://cloud.githubusercontent.com/assets/16018638/11400376/fd14cc3e-93c7-11e5-9f93-42a12c26e669.png)

**Comment by sgsinclair** [comment]
Thanks for this report! It looks like the tokenization / word segmentation is finicky with the new analysis engine. In some cases it seems to treat all Chinese characters individually as words, in other cases it does seem to be doing proper grouping (at least of bigram characters). I hesitate to throw out the entire analyzer since it does deal with many instances of language better, but I think I might need to add a user option to say essential: revert to plain old segmentation based on non-word character boundaries (the trade-off is that some languages have very long character sequences that really should be tokenized).

Could you please attach an example file for the Chinese (or create a gist)?

BTW, for version 1, if you start with http://voyant-tools.org/?forceHtml5=true Cirrus at least should work.

**Comment by ip1200** [comment]
Actually, Chinese segment is conducted by a software which is called NLPIR (http://ictclas.nlpir.org/) before uploading to voyant tools. I guess that the beta ignores the spaces which segment different meaning groups.
Attached are two examples of a same document, one is original, and the other is segmented with the help of NLPIR.
Segmented
[1954_Segmented.txt](https://github.com/sgsinclair/Voyant/files/44628/1954.txt)
Original
[1954_Original.txt](https://github.com/sgsinclair/Voyant/files/44629/1954.txt)

**Comment by sgsinclair** [comment]
These are very useful, thanks. I created a simplified view of these files for unit testing and am currently producing the following results, which seem encouraging to me:

* i18n/zh_utf8.txt: 我们第一届全国人民代表大会第一次会议
	* built-in tokenizer: 10 tokens
	* word boundaries tokenizer: 1 token
* i18n/zh_segmented_utf8.txt: 我们 第一 届 全国人民代表大会 第 一次 会议
	* built-in tokenizer: 9 tokens
	* word boundaries tokenizer: 7 tokens

**Comment by ip1200** [comment]
Nice work！I hope the option for choosing tokenizer can be added to the newer beta (or final) version~
Attached is the stoplist of Chinese which I used in analyzing the government work report. I think it might be useful.
BTW, I find the streamgraph is very interesting, and indeed make sense. Thus I have a dream that you can add it to the Trends Tool. I googled and find there is no tool that can generate a streamgraph online with the data given by the user friendly. (R can, but too complex for a beginner)
If interested in, you may find some useful code on Github (e.g. https://github.com/leebyron/streamgraph) under the BSD licensen and someting else on http://bl.ocks.org/mbostock/4060954
Attachment
[sotplist_CN.txt](https://github.com/sgsinclair/Voyant/files/45327/sotplist_CN.txt)

**Comment by sgsinclair** [comment]
This should be included in the next beta release, hopefully by the end of next week (early December 2015).

<img width="677" alt="tokenizationui" src="https://cloud.githubusercontent.com/assets/355388/11446471/6fe83ad2-9505-11e5-9471-7915108a4675.png">

Please feel free to create another issue for a steamgraph with suggested functionality. I may not get to it as quickly since it's more of a feature request than a bug, but I too think it would be a nice addition.

**Comment by sgsinclair** [comment]
17dd68d7ebbc07b5e2314e078f02ce2a8443a0b6
