### ISSUE TITLE
Voyantserver cannot display chinese character properly

### ISSUE THREAD

**Issue by ip1200** [sgsinclair/Voyant#254]
when using voyantserv M7, after uploading the file coded with Unicode, the circus cannot dispaly Chinese character properly(mess code), and the reader shows sturcure labels of txt file such as </br>
hope this can be solved.
However, when use the webapp on betavoyant, it works well.

**Comment by ip1200** [comment]
![ashampoo_snap_2016 01 06_20h13m59s_001_](https://cloud.githubusercontent.com/assets/16018638/12142404/d30b4704-b4b2-11e5-8401-0498c9dd01c7.png)

**Comment by sgsinclair** [comment]
This is probably due to Java using a different character encoding on your system than UTF-8, this commit should fix it:

https://github.com/sgsinclair/VoyantServer/commit/4547650bb0f7cb152405f1be31b13a3684c9d327#diff-ffdb46ee8f8000b2eac731ce9a690c16R87

I hope to upload a new build by the end of the week that you can test. I'll close this for now, but please reopen if needed.
