### ISSUE TITLE
  web proxy server rewrite problems

### ISSUE THREAD

**Issue by susanmonnelly** [sgsinclair/Voyant#458]
Hello

We are implementing  Voyant within our product and have installed the Voyant server internally.    We primarily sell database products to libraries.   These institutions typically use web proxy servers that  give access from outside the library's computer network to restricted-access websites like ours. This allows library patrons at home or elsewhere to log in through their library's proxy server and gain access to resources to which their library subscribes, such as bibliographic databases.   

The implementation of these proxy servers requires the URLs to be rewritten including javascript network resources.   We are having a couple fo specific problems when clicking on a Voyant tool and the launching of the Cirrus panel to open in new window.  At that point our URLs are not rewritten but are then running outside the proxied server.    

Here's a screenshot that may help:

![71731712-71fec600-2e13-11ea-8cc7-1f2f42aba274 (1)](https://user-images.githubusercontent.com/12297503/71904983-33c81600-3135-11ea-8018-bbc973cf400d.png)

 the base URL in the browser is 

https://ourdomain.idm.oclc.org/apps/readex/voyant

but the base URL in the Voyant code is //ourdomain.com/voyant/

We attempted to rewrite that URL through our web proxy server configuration without success.

Can you help us understand where this baseUrl is coming from and why it is not the same as the URL from the main window.

```
	Ext.application({
		extend : 'Voyant.VoyantToolApp',
//		requires: ['Voyant.panel.VoyantHeader','Voyant.panel.Cirrus','Voyant.panel.VoyantFooter'],
		name : 'VoyantToolApp',
		config: {
			baseUrl: '//ourdomain.com/voyant/',
			version: '2.4',
			build: 'M17',
			tool: 'cirrus',
			allowInput: ''
```

Thanks for any help you can provide

Susan

**Comment by sgsinclair** [comment]
So sorry about the delay in replying, I'm digging myself out from an avalanche of email over the holidays.

So that URL is generated here:

https://github.com/sgsinclair/Voyant/blob/master/src/main/webapp/index.jsp#L47

In other words, here:

https://github.com/sgsinclair/Voyant/blob/master/src/main/java/org/voyanttools/voyant/Voyant.java#L60

There's probably a way of specifying the server name from the proxy. How are you launching Voyant, from the command line? I haven't tested it, but maybe something like this?

-Djetty.http.host=ourdomain.idm.oclc.org

As a stop-gap measure you could simply modify the code from the first link to match your server environment (but of course you'll need to do that every time you update the server).

**Comment by susanmonnelly** [comment]
Thanks for the help !

A few things to clarify: 

- We do not call the voyant tool from the command line. We are implementing this tool with an application through a web browser.  
- We have many customers with different server domain rewrites so we can't predict the URL.   

Do you know where could we change the code to use the client domain  for the base URL and in place of the server domain?

Thanks

**Comment by rparadis** [comment]
Hello @sgsinclair,

I am working with @susanmonnelly to solve our client proxy customers.   I was able to change several (7 to be exact) of the `index.jsp` pages so that the baseUrl was no longer protocol insensitive by simply injecting the https: string into the baseUrl.  This is important for the client proxies to identify the URL so that they care rewrite it correctly.   I am happy to report everything works correctly.

**code example:**
`        Ext.application({
                extend : 'Voyant.VoyantCorpusApp',
                requires: ['Voyant.panel.Subset'],
                name: 'VoyantDreamApp',
                config: {
                        baseUrl: 'https:<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',
`

I did try to update the server side code to include the protocol eg. `request.getScheme()` but the server itself is not secured (as it is being served through haproxy for ssl).  That is a conundrum.  

I'm trying to determine if there is a more robust solution... and possibly one that doesn't involve us having to modify/branch from the original code base.  Any ideas?

Thanks again!
- Roger

**Comment by sgsinclair** [comment]
Could you please say a bit more about how the web application is launched and run, or does it depend on the client? I'm trying figure out a way for you to define an override parameter but it depends on how it's run (Jetty, Tomcat, etc.). The ideal would be if we could set an environment variable so that no code or configuration value would need to be changed with each Voyant update.

**Comment by susanmonnelly** [comment]
Thanks,   I consulted with our TechOps person who installed Voyant on a development server.   It's run with Tomcat through haproxy but not sure if the latter matters.   Is there any other detail that you need?

**Comment by susanmonnelly** [comment]
@sgsinclair We haven't heard back in a couple of weeks and wondering if you have any thoughts here.   Have I answered your questions enough to help? 

We could create our own branch since our problem is fixed with some code changes but as you said an ideal solution would be a configuration update.

Thanks for any help you can provide.

Susan

**Comment by susanmonnelly** [comment]
@sgsinclair ,

We're at the point where we are configuring our production environments for our voyant server.  If we were to run this with the jar file like this:
java -jar VoyantServer.jar --headless=true. 

What are the configurations that we could add to the command line to  
alter the base URL for the tools to not use the protocol relative urls.    

Or does this not exist yet?

Unfortunately if we don't have an alternative we'll need to create fork off this code base and create our own installation.

Thanks for any help
Susan

**Comment by ajmacdonald** [comment]
Hello @susanmonnelly,
Have you had any luck with this?
I must sadly report that sgsinclair has passed away and I am currently the primary maintainer of Voyant. My knowledge of the server configuration is not as robust as his was, but I will try to assist if I'm able.

Andrew

**Comment by susanmonnelly** [comment]
Andrew -  I'm so sorry to hear about Stefan's passing.

We have gotten around the problem, although it was so long ago I don't remember what we did.  
I think we had to make changes to our installation 
Thanks for checking in 

Susan
