### ISSUE TITLE
Corpus Terms not including all documents in corpus

### ISSUE THREAD

**Issue by kagoudie** [sgsinclair/Voyant#483]
I have 132 documents in my corpus, but the sparkline graphs generated by Corpus Terms tool only includes the first 100 documents. Is this by design or have I missed an option somewhere?

**Comment by ajmacdonald** [comment]
Hello @kagoudie,
This is by design and is for performance reasons.
While all the documents are included when performing the Corpus Terms analysis, in the case of a corpus with more than 100 documents the distribution results are binned into 100 bins for display in the sparkline.
The document title displayed in the sparkline tool tip assumes that the number of documents will be 100 or less, but in your case this will be erroneous.
